version: '3.4'

services:
  seafarerscafesite:
    image: seafarerscafesite
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
