version: '3.4'

services:
  db:
    image: mysql/mysql-server
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - ${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - my-db:/var/lib/mysql

  seafarerscafesite:
    image: seafarerscafesite
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${FRONTEND_PORT}
    expose:
      - ${API_PORT}
    depends_on:
      - "db"

volumes:
  my-db:
