version: '3.4'

services:
  db:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - server-db:/bitnami/mysql/data

  backend:
    image: seafarerscafesiteapi
    build:
      context: ./app/backend
      dockerfile: ./Dockerfile
    command: sh -c 'dockerize -wait tcp://db:${DB_PORT} -timeout 300s -wait-retry-interval 15s npm start'
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - './app/backend:/backend'
      - './backend/node_modules'
    depends_on:
      - 'db'

  frontend:
    image: seafarerscafesite
    build:
      context: ./app/frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - './app/frontend:/frontend'
      - './frontend/node_modules'
    depends_on:
      - 'backend'

volumes:
  server-db:
