version: '3.4'

services:
  db:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - server-db:/bitnami/mysql/data

  api:
    image: seafarerscafesiteapi
    command: sh -c 'dockerize -wait tcp://db:${DB_PORT} -timeout 300s -wait-retry-interval 15s npm start'
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - '.:/app/api'
      - '.:/app/api/node_modules'
    depends_on:
      - 'db'

  frontend:
    image: seafarerscafesite
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    depends_on:
      - 'api'

volumes:
  server-db:
